// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBXZuVP7dtCEW8Ex0MTqTINuLf_jaDnsg',
    appId: '1:632279731667:web:290e46270b7e7571d27326',
    messagingSenderId: '632279731667',
    projectId: 'test-42c4d',
    authDomain: 'test-42c4d.firebaseapp.com',
    storageBucket: 'test-42c4d.appspot.com',
    measurementId: 'G-36S47X8F80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhe2m5UzjyvN5LkLlvD_35fqXuXyfKaes',
    appId: '1:632279731667:android:dc2bc942e0c61144d27326',
    messagingSenderId: '632279731667',
    projectId: 'test-42c4d',
    storageBucket: 'test-42c4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIS4q4SwpxSTZEESELpSgLJ0bIr58yYGg',
    appId: '1:632279731667:ios:a9877868951a1a6cd27326',
    messagingSenderId: '632279731667',
    projectId: 'test-42c4d',
    storageBucket: 'test-42c4d.appspot.com',
    androidClientId: '632279731667-57cum63bh5mpirofq6bnm82vjf6isi9q.apps.googleusercontent.com',
    iosClientId: '632279731667-qo8le6e56qp95a6sgb78qdnaedjoio6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIS4q4SwpxSTZEESELpSgLJ0bIr58yYGg',
    appId: '1:632279731667:ios:a9877868951a1a6cd27326',
    messagingSenderId: '632279731667',
    projectId: 'test-42c4d',
    storageBucket: 'test-42c4d.appspot.com',
    androidClientId: '632279731667-57cum63bh5mpirofq6bnm82vjf6isi9q.apps.googleusercontent.com',
    iosClientId: '632279731667-qo8le6e56qp95a6sgb78qdnaedjoio6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
